# Generated by Django 4.1.7 on 2023-04-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cart',
            new_name='favorites',
        ),
    ]
