# Generated by Django 4.1.7 on 2023-03-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cart',
            field=models.ManyToManyField(null=True, to='api.product'),
        ),
    ]
