# Generated by Django 4.1.7 on 2023-03-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
